version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: golang-app
    container_name: goanis-app
    restart: unless-stopped
    ports:
      - "8010:8011"
    networks:
      - anis

networks:
  anis:
    driver: bridge

volumes:
  db_data:
    driver: local
