package enums

const DEFAULT_PORTFOLIO_PAGE_STRING = "1"
const DEFAULT_PORTFOLIO_LIMIT_STRING = "6"
const DEFAULT_PORTFOLIO_PAGE_INTEGER = 1
const DEFAULT_PORTFOLIO_LIMIT_INTEGER = 6

const DEFAULT_TESTIMONIAL_PAGE_STRING = "1"
const DEFAULT_TESTIMONIAL_LIMIT_STRING = "3"
const DEFAULT_TESTIMONIAL_PAGE_INTEGER = 1
const DEFAULT_TESTIMONIAL_LIMIT_INTEGER = 3
